[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fets2022-flower"
version = "1.1.6"
description = "FeTS 2022 3D MRI Federated Brain Tumor Segmentation with Flower"
license = {file = "LICENSE"}

requires-python = ">=3.11,<3.13"
dependencies = [
    "flwr[simulation]>=1.37.0",
    "torch==2.14.0",
    "monai==1.6.0",
    "nibabel==5.4.2",
    "pandas==3.0.6",
    "matplotlib>=3.8",
    "scipy==1.17.1",
    "numpy==2.4.1",
    "pytest>=8.0.0",
]

#[tool.uv.sources]
#torch = [
#    { index = "pytorch-cu128" },
#]
#torchvision = [
#    { index = "pytorch-cu128" },
#]

#[[tool.uv.index]]
#name = "pytorch-cu128"
#url = "https://download.pytorch.org/whl/cu128"
#explicit = true

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"
fab-format-version = 1
flwr-version-target = "1.37.0"

[tool.flwr.app.components]
serverapp = "server_app:app"
clientapp = "client_app:app"

[tool.flwr.app.config]
data-root = "data/MICCAI_FeTS2022_TrainingData"
partition-csv = "data/MICCAI_FeTS2022_TrainingData/partitioning_1.csv"
num-server-rounds = 5

fraction-train = 1.0
fraction-evaluate = 1.0
local-epochs = 1
learning-rate =  0.00005
batch-size = 1
global-test-fraction = 0.15

fraction-fit = 1.0
num-clients = 23
safe-model = true
algorithm = "fedavg"
proximal_mu = 0.01
model_name = "3DUnet"

# Client Participation ("fixed" or "sliding")
collaborator-selector = "fixed"
collaborator-fraction = 0.2
collaborator-selector-seed = 42

# RegSimAgg Hyperparameters (Temporal Damping & Distance Metric)
regsimagg-regularization-round = 10
regsimagg-distance-mode = "paper_l1"
